name = "HelmholtzBenchmark"
uuid = "f8c70973-57d2-49de-b940-018be9beacc3"
authors = ["Daniel Runge <runge@wias-berlin.de>, Zeina Amer <amer@wias-berlin.de>, Marieke Osewold <osewold@wias-berlin.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataFrames = "1.7.0"
DrWatson = "2.19.0"
LinearSolve = "2"
Plots = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
